import { useEffect, useState } from 'react';
import type { FormEvent, ReactElement } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase } from './supabase';
import type { Booking } from './supabase';
import './styles.css';
import './footer.css';
import './admin.css';
import './mobile.css';
import './products.css';
import './navbar.css';
import './shop.css';
import './catalogue.css';
import './mobile-tight.css';
import './bento-fit.css';
import './loader.css';
import './collection.css';
import './brand.css';
import './collection-grid.css';
import './collection-polish.css';
import './menu.css';
import './collection-intro.css';
import './booking.css';
import './admin-functional.css';
import './icons.css';

const services: string[] = ['Dermatology', 'General Check-Ups & Consultations', 'Emergency Care', 'Dental Care', 'Surgery', 'Vaccinations & Preventive Care', 'Grooming & Wellness', 'Diagnostics'];
const ArrowIcon = ({ direction = 'right' }: { direction?: 'right' | 'down' | 'down-right' | 'left' }): ReactElement => <svg className={`icon icon-${direction}`} viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>;
const SparkIcon = (): ReactElement => <svg className="hero-star" viewBox="0 0 40 40" aria-hidden="true"><path d="M20 1c2.1 11.4 7.6 16.9 19 19-11.4 2.1-16.9 7.6-19 19-2.1-11.4-7.6-16.9-19-19C12.4 17.9 17.9 12.4 20 1Z" fill="currentColor"/></svg>;
const PhoneIcon = (): ReactElement => <svg className="contact-phone" viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 3.5 9.3 7l-1.7 2.1c1.1 2.3 2.9 4.1 5.2 5.2l2.1-1.7 3.5 2.7-1 3.6c-.2.7-.9 1.2-1.7 1.1C8.8 19.3 4.7 15.2 4 8.3c-.1-.8.4-1.5 1.1-1.7l1.5-3.1Z" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinejoin="round"/></svg>;
const HeartIcon = (): ReactElement => <svg className="quote-heart" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.8a5.3 5.3 0 0 0-7.5 0L12 6.1l-1.3-1.3a5.3 5.3 0 1 0-7.5 7.5L12 21l8.8-8.7a5.3 5.3 0 0 0 0-7.5Z" fill="none" stroke="currentColor" strokeWidth="2"/></svg>;

function ClinicSite(): ReactElement {
  const [bookingMessage, setBookingMessage] = useState('');
  const submitBooking = async (event: FormEvent<HTMLFormElement>): Promise<void> => {
    event.preventDefault();
    const form = event.currentTarget;
    if (!supabase) { setBookingMessage('Booking setup is incomplete. Please contact the clinic directly.'); return; }
    setBookingMessage('Sending your request…');
    const formData = new FormData(form);
    const { error } = await supabase.from('bookings').insert({
      owner_name: String(formData.get('owner_name') || ''), animal_name: String(formData.get('animal_name') || ''),
      phone: String(formData.get('phone') || ''), service: String(formData.get('service') || ''),
    });
    if (error) { setBookingMessage('We could not send your request. Please try again or call us.'); return; }
    form.reset(); setBookingMessage('Request received — we’ll contact you shortly.');
  };
  return <main>
    <section className="hero" id="home">
      <nav><a className="brand" href="#home">APOK</a><div className="links"><a href="#services">Services</a><a href="#products">Products</a><a href="#about">About</a><a href="#contact">Contact</a></div><a className="nav-book" href="#contact">Book a visit</a><details className="mobile-menu"><summary aria-label="Open navigation"><span></span><span></span><span></span></summary><div><a href="#services">Services</a><a href="#products">Products</a><a href="#about">About</a><a href="#contact">Contact</a><a className="menu-book" href="#contact">Book a visit →</a></div></details></nav>
      <div className="hero-copy"><small>Veterinary care · pets + families</small><h1>Because<br/>They<br/>Deserve<br/>The Best.</h1><p>Good medicine. Warm hands. Real answers for the animals who make life better.</p><div className="hero-actions"><a className="button black" href="#services">Explore care</a><a className="button yellow" href="#contact">Book a visit</a></div></div>
      <SparkIcon /><img className="hero-dog" src="https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=900&q=90" alt="Happy brown dog" />
    </section>
    <section className="services" id="services"><div className="services-heading"><p className="eyebrow">What we do</p><h2>Care for every<br/>kind.</h2><p>From first checkups to urgent visits and whole-herd health plans.</p></div><div className="service-grid">{services.slice(0,6).map((service, index) => <article key={service}><b><ArrowIcon direction="down-right"/></b><h3>{service}</h3><p>{index === 0 ? 'Thoughtful nose-to-tail care for every stage of life.' : 'Practical care with calm, responsive attention.'}</p></article>)}</div></section>
    <section className="shop" id="products"><div className="shop-heading"><div><p className="eyebrow">From our shelves</p><h2>Pet shop essentials.</h2></div><p>Food, carriers, treats and everyday accessories for the animals you love.</p></div><div className="shop-grid">{[['/products/dog-food.jpeg', 'Dog food', 'Chiwawa and Club 4 Paws food'], ['/products/nodule-pet-food.jpeg', 'Nodule pet food', 'Delicious food for dogs and cats'], ['/products/collars-leads.jpeg', 'Collars & leads', 'For every walk'], ['/products/cat-treats.jpeg', 'Cat treats', 'A little something special'], ['/products/pet-carriers.jpeg', 'Pet carriers', 'Safe, comfortable trips'], ['/products/pet-shampoo.jpeg', 'Pet shampoo', 'Fresh coat care for pets'], ['/products/retractable-leads.jpeg', 'Retractable leads', 'Easy walks, better control']].map(([image, title, description]) => <article key={title}><img src={image} alt={title}/><div><h3>{title}</h3><p>{description}</p></div></article>)}</div><a className="collection-link" href="#collection">View full product collection　→</a></section>
    <section className="about" id="about"><div className="about-cut"></div><div className="megaphone">◖</div><div className="about-content"><p className="eyebrow">A little more love</p><h2>About Us</h2><article><h3>We’re all about paws &amp; hearts</h3><p>More than just vets — we’re animal lovers, treat-givers, and belly-rub experts. Every visit is about keeping tails wagging, whiskers twitching, and pets thriving.</p></article><article><h3>Care that feels like family</h3><p>From check-ups to emergencies, we mix modern medicine with genuine love. Because every bark, every purr, and every cuddle deserves nothing less.</p></article><div className="mini-stats"><span><b>5k+</b>happy tails</span><span><b>7 days</b>here for you</span></div><a className="button black" href="#contact">Book Your First Appointment</a></div></section>
    <section className="quote"><HeartIcon /><blockquote>“They kept Biscuit calm, explained every step, and treated us like family.”</blockquote><p>Rebecca M. · Biscuit’s person</p></section>
    <section className="contact" id="contact"><div className="contact-copy"><p className="eyebrow">Come say hello</p><h2>Let’s look after<br/>them.</h2><div><p>No. 128 Enu-Ifite<br/>Awka, Anambra State</p><p className="phone-line"><PhoneIcon /><span><a href="tel:+2348039778902">0803 977 8902</a><br/><a href="tel:+2347003666535">0700 366 6535</a></span></p><p>Contact us to arrange your visit.</p></div></div><div className="contact-form"><p className="eyebrow">Request an appointment</p><form onSubmit={submitBooking}><label>Your name<input name="owner_name" aria-label="Your name" required /></label><label>Animal's name<input name="animal_name" aria-label="Animal's name" required /></label><label>Phone number<input name="phone" type="tel" aria-label="Phone number" required /></label><label>What do you need?<select name="service" aria-label="Visit type" defaultValue="Wellness visit"><option>Wellness visit</option><option>Emergency care</option><option>General consultation</option></select></label><button type="submit">Send request <ArrowIcon /></button>{bookingMessage && <p className="booking-message" role="status">{bookingMessage}</p>}</form></div></section>
    <footer><a className="footer-brand" href="#home">APOK ANIMAL PHARMACY</a><p>Care for pets, farms &amp; everything between.</p><div className="socials"><a href="https://www.instagram.com/apokagricultural?stkn=MTBpcDF3MHNoMjcy" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.facebook.com/share/19Jx97QNTL/" target="_blank" rel="noreferrer">Facebook ↗</a></div><small>© {new Date().getFullYear()} Apok Animal Pharmacy</small></footer>
  </main>;
}

function AdminPanel(): ReactElement { const [bookings, setBookings] = useState<Booking[]>([]); const loadBookings = async (): Promise<void> => { if (!supabase) return; const { data } = await supabase.from('bookings').select('*').order('created_at', { ascending: false }); setBookings((data as Booking[] | null) ?? []); }; useEffect(() => { void loadBookings(); }, []); const updateStatus = async (id: string, status: Booking['status']): Promise<void> => { if (!supabase) return; await supabase.from('bookings').update({ status }).eq('id', id); await loadBookings(); }; const pending = bookings.filter((booking) => booking.status === 'pending').length; const confirmed = bookings.filter((booking) => booking.status === 'confirmed').length; return <div className="admin"><aside className="admin-side"><a href="#home" className="admin-logo">APOK<br/>DESK.</a><nav><a className="active" href="#admin">Appointments <b>{bookings.length}</b></a></nav><div className="side-user"><span>AO</span><p>Apok Admin<br/><small>Clinic Manager</small></p></div></aside><section className="admin-main"><header><div><p className="eyebrow">Booking management</p><h1>Appointments</h1></div><a href="#home">← View website</a></header><div className="metrics"><article><small>All booking requests</small><b>{bookings.length}</b><em>From your website</em></article><article><small>Pending requests</small><b>{pending}</b><em>Needs your review</em></article><article><small>Confirmed bookings</small><b>{confirmed}</b><em>Ready for the clinic</em></article></div><section className="appointments appointments-wide"><div className="panel-title"><div><p className="eyebrow">Live queue</p><h2>Booking requests</h2></div><button type="button" onClick={() => void loadBookings()}>Refresh</button></div><div className="booking-list">{bookings.length === 0 ? <p className="empty-bookings">No bookings yet. New booking requests will appear here.</p> : bookings.map((booking) => <article key={booking.id}><time>{new Date(booking.created_at).toLocaleDateString()}</time><div><b>{booking.animal_name}</b><small>{booking.owner_name} · {booking.phone}</small></div><span>{booking.service}</span><select value={booking.status} onChange={(event) => void updateStatus(booking.id, event.target.value as Booking['status'])} aria-label={`Status for ${booking.animal_name}`}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option></select></article>)}</div></section></section></div> }
function AdminAccess(): ReactElement { const [signedIn, setSignedIn] = useState(false); const [authorized, setAuthorized] = useState(false); const [checking, setChecking] = useState(true); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const checkAccess = async (): Promise<void> => { if (!supabase) { setChecking(false); return; } const { data: { session } } = await supabase.auth.getSession(); setSignedIn(Boolean(session)); if (!session) { setAuthorized(false); setChecking(false); return; } const { data } = await supabase.rpc('is_admin'); setAuthorized(data === true); setChecking(false); }; useEffect(() => { void checkAccess(); if (!supabase) return; const { data: listener } = supabase.auth.onAuthStateChange(() => { setChecking(true); void checkAccess(); }); return () => listener.subscription.unsubscribe(); }, []); const sendLink = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); if (!supabase) { setMessage('Supabase configuration is missing.'); return; } const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/#admin` } }); setMessage(error ? error.message : 'Check your email for the secure sign-in link.'); }; if (checking) return <main className="admin-login"><p>Checking secure access…</p></main>; if (signedIn && authorized) return <AdminPanel />; if (signedIn) return <main className="admin-login"><section><p className="eyebrow">Access restricted</p><h1>Not authorized</h1><p>This email has not been added to the APOK admin list.</p><a href="#home">← Back to website</a></section></main>; return <main className="admin-login"><form onSubmit={sendLink}><p className="eyebrow">Apok Animal Pharmacy</p><h1>Admin sign in</h1><p>Use an approved clinic email to receive a secure access link.</p><label>Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><button type="submit">Send sign-in link</button>{message && <small>{message}</small>}<a href="#home">← Back to website</a></form></main> }
function Loader(): ReactElement { return <div className="loader" aria-label="Loading"><div className="loader-bone" aria-hidden="true"></div></div>; }
function CollectionPage(): ReactElement { return <main className="collection-page"><header className="collection-nav"><a className="brand" href="#home">APOK</a><a className="nav-book" href="#home">← Back to site</a></header><section className="collection-hero"><div><p className="eyebrow">Apok Animal Pharmacy · Awka</p><h1>Pet shop,<br/>properly stocked.</h1></div><div><p>Browse our in-store range of food, care essentials, carriers, leads and more.</p><a href="#collection-grid">Explore products ↓</a></div></section><section className="collection-content" id="collection-grid"><div className="collection-intro"><p className="eyebrow">In store collection</p><h2>Browse what’s on our shelves.</h2></div><div className="collection-feature"><img src="/products/catalogue/product-13.jpeg" alt="Apok pet shop collection"/><div><p className="eyebrow">In store now</p><h2>Everything for their everyday.</h2><p>Find familiar food brands, care supplies and the little extras pets love.</p></div></div><div className="catalogue-gallery">{Array.from({ length: 26 }, (_, index) => <figure className={`tile tile-${index + 1}`} key={index}><img src={`/products/catalogue/product-${String(index + 1).padStart(2, '0')}.jpeg`} alt={`Apok product ${index + 1}`}/><figcaption><span>Apok product</span><b>Available in store</b></figcaption></figure>)}</div></section></main> }
function App(): ReactElement { const [page, setPage] = useState(window.location.hash); const [loading, setLoading] = useState(true); useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 900); return () => window.clearTimeout(timer); }, []); useEffect(() => { const sync = () => setPage(window.location.hash); window.addEventListener('hashchange', sync); return () => window.removeEventListener('hashchange', sync); }, []); return loading ? <Loader /> : page === '#admin' ? <AdminAccess /> : page === '#collection' ? <CollectionPage /> : <ClinicSite />; }
createRoot(document.getElementById('root')!).render(<App />);
